name: 'Github Actions Job info'
description: |
  Obtains job metadata from the GitHub Actions API.
  Provides this as a file on disk, job_info.json.

  If debug logging is enabled, this action will save an additional file,
  all_jobs.json, that captures all jobs in the pipeline. This is useful
  for troubleshooting misbehaving spans.

runs:
  using: 'composite'
  steps:
    - uses: actions/github-script@v7
      id: get-job-info
      with:
        retries: 3
        script: |
          const fs = require('node:fs')
          const runAttempt = parseInt(process.env.GITHUB_RUN_ATTEMPT, 10)

          get_job = async ({github, context, process}) => {
            const opts = github.rest.actions.listJobsForWorkflowRunAttempt.endpoint.merge(
                {
                    attempt_number: runAttempt,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    run_id: context.runId,
                    per_page: 100
                });
            const jobs = await github.paginate(opts);

            if (core.getBooleanInput('debug') || core.isDebug()) {
              try {
                fs.writeFileSync('all_jobs.json', JSON.stringify(jobs));
              } catch(err) {
                console.error(err)
                throw(err)
              }
            }

            // We know what the run ID is, but we don't know which specific job we're being run from.
            // https://github.com/orgs/community/discussions/8945
            return jobs.find((job) => {
                return job.runner_name === process.env.RUNNER_NAME && job.run_attempt === runAttempt;
            });
          };

          var this_job = undefined;
          var retryCount = 0;
          maxRetries = 5;
          initialDelay = 2000;
          while (this_job === undefined) {
            this_job = await get_job({github, context, process});
            if (this_job === undefined && retryCount < maxRetries) {
              retryCount++;
              await new Promise(res => setTimeout(res, initialDelay * Math.pow(2, retryCount - 1)));
            } else {
              break;
            }
          }

          if (this_job === undefined){
            github.log.error("Telemetry values were not available. Please see debug logs for more info.");
            github.log.error("All jobs:");
            const jobs = await get_job({github, context, process});
            github.log.error(JSON.stringify(jobs));

            throw "Telemetry values were not available. Please see debug logs for more info."
          }
          try {
            fs.writeFileSync('job_info.json', JSON.stringify(this_job));
          } catch(err) {
           console.error(err)
           throw(err)
          }
    - name: Upload job_info_json if in debug mode
      if:  runner.debug == '1'
      uses: actions/upload-artifact@v4
      with:
        name: github-job-info
        path: all_jobs.json
