name: changed-files
description: Check changed files in a PR
inputs:
  files_yaml:
    description: |
      YAML string containing mappings of the form `{key}: [{glob1}, {glob2}, etc.]`.
      Where `{key}` is an arbitrary identifier for grouping a set of changed files
      (e.g. "test_cpp" for "if these files change, C++ tests should be re-run") and
      each `{glob}` is a glob expression matching file paths in the calling repo.
      For example, "re-run all C++ tests on any changes EXCEPT docs" might look like this:
      'test_cpp: ["**", "!docs/**"]'.
    type: string
    required: true
  transform_expr:
    description: |
      jq expression for post-processing results to create this workflow's outputs.
      Provided for backwards compatibility; should not need to be updated with normal use.
    type: string
    required: false
    default: |
      to_entries |
      map(
        select(.key | endswith("_any_changed")) |
        {
          "key": (.key | rtrimstr("_any_changed")),
          "value": .value,
        }
      ) |
      from_entries

runs:
  using: composite
  steps:
    - name: Get PR info
      id: get-pr-info
      uses: nv-gha-runners/get-pr-info@main
    - name: Checkout code repo
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Calculate merge base
      id: calculate-merge-base
      shell: bash
      env:
        PR_SHA: ${{ fromJSON(steps.get-pr-info.outputs.pr-info).head.sha }}
        BASE_SHA: ${{ fromJSON(steps.get-pr-info.outputs.pr-info).base.sha }}
      run: |
        (echo -n "merge-base="; git merge-base "$BASE_SHA" "$PR_SHA") | tee --append "${GITHUB_OUTPUT}"
    - name: Get changed files
      id: changed-files
      uses: step-security/changed-files@95b56dadb92a30ca9036f16423fd3c088a71ee94 # v46.0.5
      with:
        base_sha: ${{ steps.calculate-merge-base.outputs.merge-base }}
        sha: ${{ fromJSON(steps.get-pr-info.outputs.pr-info).head.sha }}
        files_yaml: ${{ inputs.files_yaml }}
        write_output_files: true
        json: true
    - name: Transform changed files into output
      id: transform-changed-files
      shell: bash
      env:
        TRANSFORM_EXPR: ${{ inputs.transform_expr }}
      run: |
        file_args=()
        for file in .github/outputs/*.json; do
          key="$(echo "$file" | sed -E 's/^\.github\/outputs\/(.*)\.json$/\1/g')"
          file_args=("${file_args[@]}" --slurpfile "$key" "$file")
        done
        (echo -n "transformed-output="; jq -c -n "\$ARGS.named | to_entries | map({\"key\": .key, \"value\": .value[]}) | from_entries | $TRANSFORM_EXPR" "${file_args[@]}") | tee --append "${GITHUB_OUTPUT}"
        echo "Contents of ${GITHUB_OUTPUT}:"
        cat "${GITHUB_OUTPUT}"
