name: changed-files
description: Check changed files in a PR
inputs:
  files_yaml:
    description: |
      YAML string containing mappings of the form `{key}: [{glob1}, {glob2}, etc.]`.
      Where `{key}` is an arbitrary identifier for grouping a set of changed files
      (e.g. "test_cpp" for "if these files change, C++ tests should be re-run") and
      each `{glob}` is a glob expression matching file paths in the calling repo.
      For example, "re-run all C++ tests on any changes EXCEPT docs" might look like this:
      'test_cpp: ["**", "!docs/**"]'.
    type: string
    required: true
  transform_expr:
    description: |
      jq expression for post-processing results to create this workflow's outputs.
      Provided for backwards compatibility; should not need to be updated with normal use.
    type: string
    required: false
    default: |
      to_entries |
      map(
        select(.key | endswith("_any_changed")) |
        {
          "key": (.key | rtrimstr("_any_changed")),
          "value": .value,
        }
      ) |
      from_entries
outputs:
  changed_file_groups:
    value: ${{ steps.transform-changed-files.outputs.transformed-output }}

runs:
  using: composite
  steps:
    - name: Get PR info
      id: get-pr-info
      uses: nv-gha-runners/get-pr-info@main
    - name: Fetch changed files
      shell: bash
      env:
        BASE_SHA: ${{ fromJSON(steps.get-pr-info.outputs.pr-info).base.sha }}
      run: |
        git fetch --depth 1 origin "$BASE_SHA"
    - name: Get changed files
      id: changed-files
      uses: step-security/changed-files@60967b822d3001fa82242f8d6b4ed46bc3600a68 # v47.0.1
      with:
        base_sha: ${{ fromJSON(steps.get-pr-info.outputs.pr-info).base.sha }}
        sha: ${{ fromJSON(steps.get-pr-info.outputs.pr-info).head.sha }}
        files_yaml: ${{ inputs.files_yaml }}
        write_output_files: true
        json: true
    - name: Transform changed files into output
      id: transform-changed-files
      shell: bash
      env:
        TRANSFORM_EXPR: ${{ inputs.transform_expr }}
      run: |
        file_args=()
        for file in .github/outputs/*.json; do
          key="$(echo "$file" | sed -E 's/^\.github\/outputs\/(.*)\.json$/\1/g')"
          file_args=("${file_args[@]}" --slurpfile "$key" "$file")
        done
        (echo -n "transformed-output="; jq -c -n "\$ARGS.named | to_entries | map({\"key\": .key, \"value\": .value[]}) | from_entries | $TRANSFORM_EXPR" "${file_args[@]}") | tee --append "${GITHUB_OUTPUT}"
