name: Stash base environment variables
description: |
  This is a strategy to pass environment variable values between jobs. Because the top-level env
  is not passed to child shared-workflow calls, we either have to have lots of inputs, or pass these
  environment variables another way. The idea here is that the top-level job exports these values,
  then the child shared-workflow jobs start with loading these values.

  This script should only ever be called by the top-level workflow. The child workflows should
  load this, then augment the environment in whatever way they need to (e.g. matrix values)

runs:
  using: 'composite'
  steps:
    - name: Compute traceparent
      # This sets TRACEPARENT env var, which we store below.
      # TRACEPARENT implicity depends on OTEL_SERVICE_NAME being set. This will have one value
      # for the top-level build (e.g. pr.yaml), and one value for each of the child workflows
      uses: ./shared-actions/telemetry-impls/traceparent
    - name: Write base env vars to a file
      shell: bash
      run: |
        OTEL_RESOURCE_ATTRIBUTES="${OTEL_RESOURCE_ATTRIBUTES},git.repository=${GITHUB_REPOSITORY}"
        OTEL_RESOURCE_ATTRIBUTES="${OTEL_RESOURCE_ATTRIBUTES},git.ref=${GITHUB_REF}"
        OTEL_RESOURCE_ATTRIBUTES="${OTEL_RESOURCE_ATTRIBUTES},git.sha=${GITHUB_SHA}"
        OTEL_RESOURCE_ATTRIBUTES="${OTEL_RESOURCE_ATTRIBUTES},git.job_url=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
        cat <<EOF > telemetry-env-vars
        OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-https://tempo.gha-runners.nvidia.com:4318}
        OTEL_EXPORTER_OTLP_PROTOCOL=${OTEL_EXPORTER_OTLP_PROTOCOL:-http/protobuf}
        OTEL_RESOURCE_ATTRIBUTES="${OTEL_RESOURCE_ATTRIBUTES/^,//}"
        OTEL_SERVICE_NAME="${OTEL_SERVICE_NAME}"
        SHARED_ACTIONS_REPO=${SHARED_ACTIONS_REPO}
        SHARED_ACTIONS_REF=${SHARED_ACTIONS_REF}
        START_TIME=${START_TIME:-$(date +'%s')}
        TRACEPARENT=${TRACEPARENT}
        EOF
    - name: Upload env vars file
      uses: actions/upload-artifact@v4
      with:
        name: telemetry-env-vars
        path: telemetry-env-vars
    - name: Re-export env vars so that defaults take effect
      uses: ./shared-actions/telemetry-impls/load-base-env-vars
