name: stash-base-env-vars
description: |
  Stash base environment variables

  This is a strategy to pass environment variable values between jobs. There are
  a lot of variables that need to be passed to a lot of child workflows. Because
  the top-level env is not inherited by child shared-workflow calls, we either have
  to have lots of inputs, or pass these environment variables another way. The
  idea here is that the top-level job exports these values, then the child
  shared-workflow jobs start with loading these values.

  This script should only ever be called by the top-level workflow. The child workflows should
  load this, then augment the environment in whatever way they need to (e.g. matrix values)

runs:
  using: 'composite'
  steps:
    - name: Write base env vars to a file
      shell: bash
      run: |
        TRACEPARENT=$(./shared-actions/telemetry-impls/traceparent.sh "${OTEL_SERVICE_NAME}")
        OTEL_RESOURCE_ATTRIBUTES="${OTEL_RESOURCE_ATTRIBUTES},git.repository=${GITHUB_REPOSITORY}"
        OTEL_RESOURCE_ATTRIBUTES="${OTEL_RESOURCE_ATTRIBUTES},git.ref=${GITHUB_REF}"
        OTEL_RESOURCE_ATTRIBUTES="${OTEL_RESOURCE_ATTRIBUTES},git.sha=${GITHUB_SHA}"
        OTEL_RESOURCE_ATTRIBUTES="${OTEL_RESOURCE_ATTRIBUTES},git.job_url=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
        cat <<EOF > telemetry-env-vars
        OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-https://tempo.gha-runners.nvidia.com:4318}
        OTEL_EXPORTER_OTLP_PROTOCOL=${OTEL_EXPORTER_OTLP_PROTOCOL:-http/protobuf}
        OTEL_RESOURCE_ATTRIBUTES="$(echo "${OTEL_RESOURCE_ATTRIBUTES}" | sed 's/^,//')"
        OTEL_SERVICE_NAME="${OTEL_SERVICE_NAME}"
        SHARED_ACTIONS_REPO=${SHARED_ACTIONS_REPO:-rapidsai/shared-actions}
        SHARED_ACTIONS_REF=${SHARED_ACTIONS_REF:-main}
        START_TIME="${START_TIME:-$(date +'%s')}"
        TRACEPARENT="${TRACEPARENT}"
        EOF
    - name: Upload env vars file
      uses: actions/upload-artifact@v4
      with:
        name: telemetry-tools-env-vars
        path: telemetry-env-vars
    - name: Re-export env vars so that defaults take effect
      uses: ./shared-actions/telemetry-impls/load-base-env-vars
