name: setup-sccache-dist

inputs:
  auth:
    required: true
    description: |
      The token used to authenticate with the sccache-dist build cluster.
  home:
    default: /github/home
    description: |
      The path to the job's $HOME directory.
  repo:
    default: rapidsai/sccache
    description: |
      The sccache GitHub repository from which to download the sccache binary.
  cache-slug:
    default: ""
    description: |
      The slug to use for unique actions/cache preprocessor and toolchain caches.
  log-file:
    default: /tmp/sccache.log
    description: |
      The path where sccache client should write logs.
  log-level:
    default: sccache=debug
    description: |
      The RUST_LOG-style log level at which the sccache client should emit logs.
  version:
    default: latest
    description: |
      The sccache GitHub release version to install, or "latest" to install the latest release.
  max-retries:
    default: inf
    description: |
      The number of times to retry failed distributed compilations, or "inf" to retry infinitely.
  request-timeout:
    default: 7140
    description: |
      The maximum time (in seconds) the sccache client should wait for a distributed compilation to complete.
  fallback-to-local-compile:
    default: false
    description: |
      Whether to fallback to compiling locally if the distributed compilation fails and/or max-retries is exceeded.

runs:
  using: composite
  steps:
    - name: Install sccache and configure sccache-dist
      shell: bash
      env:
        AUTH: "${{inputs.auth}}"
        REPO: "${{inputs.repo}}"
        VERSION: "${{inputs.version}}"
        LOG_FILE: "${{inputs.log-file}}"
        LOG_LEVEL: "${{inputs.log-level}}"
        MAX_RETRIES: "${{inputs.max-retries}}"
        REQUEST_TIMEOUT: "${{inputs.request-timeout}}"
        FALLBACK_TO_LOCAL_COMPILE: "${{inputs.fallback-to-local-compile}}"
      run: |
        ARCH="$(uname -m)"
        case "$ARCH" in
          x86_64 | amd64)
            SCHEDULER_URL="https://amd64.linux.sccache.rapids.nvidia.com"
            ;;
          aarch64 | arm64)
            SCHEDULER_URL="https://arm64.linux.sccache.rapids.nvidia.com"
            ;;
          *)
            echo "Unsupported CPU architecture '$ARCH'" >&2
            exit 1
            ;;
        esac

        # Install sccache to /usr/bin
        while ! tar -C /usr/bin -z --wildcards --strip-components=1 -x '*/sccache' -f <(
          if [ "${VERSION:-latest}" = latest ]; then
            # Install latest version
            wget --no-hsts -q -O- https://api.github.com/repos/${REPO}/releases/latest \
          | jq -r ".assets[] | select(.name | test(\"^sccache-v.*?-${ARCH}-unknown-linux-musl.tar.gz\$\")) | .browser_download_url" \
          | wget --no-hsts -q -O- -i-
          else
            # Install pinned version
            wget --no-hsts -q -O- "https://github.com/${REPO}/releases/download/v${VERSION}/sccache-v${VERSION}-${ARCH}-unknown-linux-musl.tar.gz"
          fi
        ); do
          sleep 10;
        done

        # Verify installation
        sccache --version
        mkdir -p "$(dirname "$LOG_FILE")"
        stat "$(dirname "$LOG_FILE")"
        ulimit -n "$(ulimit -Hn)"
        echo "nofile ulimit: $(ulimit -n):$(ulimit -Hn)"

        # Runner configuration
        export PARALLEL_LEVEL="$(ulimit -Hn)"
        export GHA_CACHE_SLUG="${{github.run_id}}-${{github.run_attempt}}-$RANDOM"
        export NVCC_APPEND_FLAGS="${NVCC_APPEND_FLAGS:+$NVCC_APPEND_FLAGS }-t=100"

        # sccache configuration
        source rapids-configure-sccache
        export SCCACHE_IDLE_TIMEOUT="0"
        export SCCACHE_ERROR_LOG="$LOG_FILE"
        export SCCACHE_SERVER_LOG="$LOG_LEVEL"

        # sccache-dist configuration
        export SCCACHE_DIST_AUTH_TOKEN="$AUTH"
        export SCCACHE_DIST_AUTH_TYPE="token"
        export SCCACHE_DIST_FALLBACK_TO_LOCAL_COMPILE="$FALLBACK_TO_LOCAL_COMPILE"
        export SCCACHE_DIST_MAX_RETRIES="$MAX_RETRIES"
        export SCCACHE_DIST_REQUEST_TIMEOUT="$REQUEST_TIMEOUT"
        export SCCACHE_DIST_SCHEDULER_URL="$SCHEDULER_URL"

        cat <<EOF | tee -a "$GITHUB_ENV"
        PARALLEL_LEVEL=$PARALLEL_LEVEL
        GHA_CACHE_SLUG=$GHA_CACHE_SLUG
        NVCC_APPEND_FLAGS=$NVCC_APPEND_FLAGS
        SCCACHE_BUCKET=$SCCACHE_BUCKET
        SCCACHE_REGION=$SCCACHE_REGION
        SCCACHE_IDLE_TIMEOUT=$SCCACHE_IDLE_TIMEOUT
        SCCACHE_ERROR_LOG=$SCCACHE_ERROR_LOG
        SCCACHE_SERVER_LOG=$SCCACHE_SERVER_LOG
        SCCACHE_DIST_AUTH_TOKEN=$SCCACHE_DIST_AUTH_TOKEN
        SCCACHE_DIST_AUTH_TYPE=$SCCACHE_DIST_AUTH_TYPE
        SCCACHE_DIST_FALLBACK_TO_LOCAL_COMPILE=$SCCACHE_DIST_FALLBACK_TO_LOCAL_COMPILE
        SCCACHE_DIST_MAX_RETRIES=$SCCACHE_DIST_MAX_RETRIES
        SCCACHE_DIST_REQUEST_TIMEOUT=$SCCACHE_DIST_REQUEST_TIMEOUT
        SCCACHE_DIST_SCHEDULER_URL=$SCCACHE_DIST_SCHEDULER_URL
        EOF

        # Start the sccache client daemon
        sccache --start-server

    - id: sccache-preprocessor-cache
      name: Setup sccache preprocessor cache
      uses: actions/cache@v4
      with:
        path: ${{inputs.home}}/.cache/sccache/preprocessor
        restore-keys: sccache-preprocessor-cache-${{ runner.os }}-${{ inputs.cache-slug }}
        key: sccache-preprocessor-cache-${{ runner.os }}-${{ inputs.cache-slug }}-${{ env.GHA_CACHE_SLUG }}

    - id: sccache-dist-toolchains-cache
      name: Setup sccache-dist client toolchains cache
      uses: actions/cache@v4
      with:
        path: ${{inputs.home}}/.cache/sccache-dist-client
        restore-keys: sccache-toolchains-cache-${{ runner.os }}-${{ inputs.cache-slug }}
        key: sccache-toolchains-cache-${{ runner.os }}-${{ inputs.cache-slug }}-${{ env.GHA_CACHE_SLUG }}
