name: dispatch-check-nightly-success
description: Clone shared-actions and dispatch to the check-nightly-success action.
inputs:
  repo:
    description: "The repository to check"
    required: true
    type: string
  repo_owner:
    description: "The org that owns the repo (default: rapidsai)"
    required: false
    default: "rapidsai"
    type: string
  workflow_id:
    description: "The workflow whose runs to check"
    required: false
    default: "test.yaml"
    type: string
  max_days_without_success:
    description: "The number of consecutive days that may go by without a successful CI run"
    required: false
    default: 7
    type: integer

runs:
  using: 'composite'
  steps:
    - name: Clone shared-actions repo
      uses: actions/checkout@v5
      with:
        repository: ${{ env.SHARED_ACTIONS_REPO || 'rapidsai/shared-actions' }}
        ref: ${{ env.SHARED_ACTIONS_REF || 'main' }}
        path: ./shared-actions
    - name: Run check-nightly-success
      uses: ./shared-actions/check_nightly_success/check-nightly-success
      with:
        repo: ${{ inputs.repo }}
        repo_owner: ${{ inputs.repo_owner }}
        workflow_id: ${{ inputs.workflow_id }}
        max_days_without_success: ${{ inputs.max_days_without_success }}
