name: dispatch-check-nightly-success
description: Clone shared-actions and dispatch to the check-nightly-success action.
inputs:
  repo:
    description: "Repository name with owner (e.g. 'rapidsai/cudf' not 'cudf')"
    required: true
    type: string
  target_branch:
    description: |
      Branch the pull request this is running on targets.
      Only statuses of nightly runs on that branch will be considered.
    required: false
    default: "main"
    type: string
  workflow_id:
    description: "The workflow whose runs to check"
    required: false
    default: "test.yaml"
    type: string
  max_days_without_success:
    description: "The number of consecutive days that may go by without a successful CI run"
    required: false
    default: 7
    type: integer

runs:
  using: 'composite'
  steps:
    - name: Clone shared-actions repo
      uses: actions/checkout@v6
      with:
        repository: ${{ env.SHARED_ACTIONS_REPO || 'rapidsai/shared-actions' }}
        ref: ${{ env.SHARED_ACTIONS_REF || 'main' }}
        path: ./shared-actions
    - name: Run check-nightly-success
      uses: ./shared-actions/check_nightly_success/check-nightly-success
      with:
        repo: ${{ inputs.repo }}
        target_branch: ${{ inputs.target_branch }}
        workflow_id: ${{ inputs.workflow_id }}
        max_days_without_success: ${{ inputs.max_days_without_success }}
