name: 'Telemetry summarize'
description: |
  Consumes job info, parses into spans, and pushes spans.

runs:
  using: 'composite'
  steps:
    - name: Clean up telemetry files
      uses: actions/github-script@v7
      #  && runner.debug != '1'
      if: always()
      with:
        retries: 3
        script: |
          const runAttempt = parseInt(process.env.GITHUB_RUN_ATTEMPT, 10)
          get_artifacts = async ({github, context, process}) => {
            const opts = github.rest.actions.listWorkflowRunArtifacts.endpoint.merge(
                {
                    attempt_number: runAttempt,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    run_id: context.runId,
                    per_page: 100
                });
            const artifacts = await github.paginate(opts);
            return artifacts;
          };

          var artifacts = undefined;
          var retryCount = 0;
          maxRetries = 5;
          initialDelay = 2000;
          while (artifacts === undefined) {
            artifacts = await get_artifacts({github, context, process});
            if (artifacts === undefined && retryCount < maxRetries) {
              retryCount++;
              await new Promise((res) => setTimeout(res, initialDelay * Math.pow(2, retryCount - 1)));
            } else {
              break;
            }
          }

          artifacts.forEach(artifact => {
            if (artifact.name.startsWith('telemetry-tools-')) {
              github.rest.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id
              });
            }
          });
