name: Create Locked Conda Environment
inputs:
  dependency-key:
    required: true
    type: string
    description: |
      The key of the dependency to generate, such as cpp, python, etc.
  arch:
    required: true
    type: string
    description: |
      The architecture to build for, such as x86_64, aarch64, etc.
  cuda-version:
    required: true
    type: string
    description: |
      The CUDA version to build for, such as 11.7, 12.1, etc.
  relock:
    type: string
    default: false
    description: |
      Whether to force a relock of the environment.

outputs:
  env-path:
    description: |
      The path to the conda environment.
    value: ${{ steps.create-env.outputs.env-path }}

runs:
  using: 'composite'
  steps:
    - name: compute lockfile filename
      id: lockfile-filename
      shell: bash
      run: |
        echo "filename=conda-lock-${{ inputs.dependency-key }}-${{ inputs.cuda-version }}-${{ inputs.arch }}.yml" >> $GITHUB_OUTPUT

    - name: Get PR number
      id: pr-number
      shell: bash
      run: |
        echo "pr-number=$(echo ${GITHUB_REF_NAME} | sed 's/.*\///')" >> $GITHUB_OUTPUT

    - name: Retrieve any existing lockfile
      uses: actions/cache@v4
      with:
        key: conda-lockfile-${{ inputs.dependency-key }}-${{ inputs.cuda-version }}-${{ inputs.arch }}-${{ steps.pr-number.outputs.pr-number }}
        path: ${{ steps.lockfile-filename.outputs.filename }}
        restore-keys: |
          conda-lockfile-${{ inputs.dependency-key }}-${{ inputs.cuda-version }}-${{ inputs.arch }}-${{ steps.pr-number.outputs.pr-number }}

    - name: Run conda-lock if needed
      shell: bash
      run: |
        set -Eeuxo pipefail
        export RAPIDS_UNZIP_DIR="$(pwd)/downloaded-packages"
        mkdir -p $RAPIDS_UNZIP_DIR
        CPP_CHANNEL=$(rapids-download-conda-from-github ${{ inputs.dependency-key }})
        ls -lRa $RAPIDS_UNZIP_DIR

        if [ ! -f "${{ steps.lockfile-filename.outputs.filename }}" ] || [ "${{ inputs.relock }}" == "true" ]; then
          mamba install -c conda-forge conda-lock
          rapids-logger "Generate ${{ inputs.dependency-key }} testing dependencies"

          ENV_YAML_DIR="$(mktemp -d)"
          CUDA_VERSION=${{ inputs.cuda-version }}

          rapids-dependency-file-generator \
            --output conda \
            --file-key test_${{ inputs.dependency-key }} \
            --prepend-channel "${CPP_CHANNEL}" \
            --matrix "cuda=${CUDA_VERSION%.*};arch=${{ inputs.arch }}" | tee "${ENV_YAML_DIR}/env.yaml"

          CONDA_ARCH="linux-$([ ${{ inputs.arch }} = 'amd64' ] && echo '64' || echo 'aarch64' )"

          conda-lock -f "${ENV_YAML_DIR}/env.yaml" --kind env -p $CONDA_ARCH

          mv conda-${CONDA_ARCH}.lock.yml ${{ steps.lockfile-filename.outputs.filename }}
        else
          rapids-logger "Skipping conda-lock as it already exists and relock is not true"
        fi

    - name: Unpin local file dependencies in lockfile
      shell: python
      run: |
        import yaml
        import os
        import re
        from pprint import pprint
        with open("${{ steps.lockfile-filename.outputs.filename }}", 'r') as f:
          lockfile = yaml.safe_load(f)
        local_file_pkg_names = {pkg.rsplit('-', 2)[0]: pkg.rsplit('-', 2)[1] for _, _, pkg_list in os.walk("downloaded-packages") for pkg in pkg_list if pkg.endswith('.conda')}
        print(local_file_pkg_names)
        edited_dependencies = []
        alpha_package_regex = re.compile(r'(.+?)a\d+$')
        for pkg in lockfile['dependencies']:
          print(pkg)
          if isinstance(pkg, str):
            pkg_name, version, build = pkg.split('=')
            if pkg_name in local_file_pkg_names:
              edited_dependencies.append(f'{pkg_name}={local_file_pkg_names[pkg_name]}')
              continue
            elif alpha_package_regex.match(version):
              version = alpha_package_regex.match(version).groups()[0]
              edited_dependencies.append(f'{pkg_name}={version}')
              continue
          edited_dependencies.append(pkg)
        lockfile['dependencies'] = edited_dependencies
        pprint(lockfile)
        with open("${{ steps.lockfile-filename.outputs.filename }}", 'w') as f:
          yaml.dump(lockfile, f)
    - name: archive lockfile for reference
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.lockfile-filename.outputs.filename }}
        path: ${{ steps.lockfile-filename.outputs.filename }}

    - name: Create environment
      shell: bash
      run: |
        rapids-mamba-retry env create --yes -f ${{ steps.lockfile-filename.outputs.filename }} -n test

        RESULTS_DIR=${RAPIDS_TESTS_DIR:-"$(mktemp -d)"}
        RAPIDS_TESTS_DIR=${RAPIDS_TESTS_DIR:-"${RESULTS_DIR}/test-results"}/
        mkdir -p "${RAPIDS_TESTS_DIR}"
        echo "RESULTS_DIR=${RESULTS_DIR}" >> $GITHUB_ENV
        echo "RAPIDS_TESTS_DIR=${RAPIDS_TESTS_DIR}" >> $GITHUB_ENV

        rapids-print-env

        rapids-logger "Check GPU usage"
        nvidia-smi
