name: "RAPIDS GitHub info"
inputs:
  repo:
    type: string
  branch:
    type: string
  date:
    type: string
  sha:
    type: string
  build_workflow_name:
    description: 'Custom workflow file name (defaults to build.yaml) to download artifacts from for tests'
    required: false
    type: string
outputs:
  rapids_repository:
    value: ${{ steps.standardize-repo-info.outputs.RAPIDS_REPOSITORY }}
  rapids_sha:
    value: ${{ steps.standardize-repo-info.outputs.RAPIDS_SHA }}
  rapids_ref_name:
    value: ${{ steps.standardize-repo-info.outputs.RAPIDS_REF_NAME }}
  rapids_nightly_date:
    value: ${{ steps.standardize-repo-info.outputs.RAPIDS_NIGHTLY_DATE }}

runs:
  using: composite
  steps:
    - name: Standardize repository information
      id: standardize-repo-info
      shell: bash
      run: | # zizmor: ignore[github-env]
        printf 'RAPIDS_REPOSITORY=%s\n' "$(printf '%s' "${INPUTS_REPO}" | tr -d '\n')" | tee --append "${GITHUB_ENV}" "${GITHUB_OUTPUT}"
        sha="${INPUTS_SHA}"
        if [[ "${sha}" == "" ]]; then
          sha=$(git rev-parse HEAD)
        fi
        printf 'RAPIDS_SHA=%s\n' "$(printf '%s' "${sha}" | tr -d '\n')" | tee --append "${GITHUB_ENV}" "${GITHUB_OUTPUT}"
        printf 'RAPIDS_REF_NAME=%s\n' "$(printf '%s' "${INPUTS_BRANCH}" | tr -d '\n')" | tee --append "${GITHUB_ENV}" "${GITHUB_OUTPUT}"
        printf 'RAPIDS_NIGHTLY_DATE=%s\n' "$(printf '%s' "${INPUTS_DATE}" | tr -d '\n')" | tee --append "${GITHUB_ENV}" "${GITHUB_OUTPUT}"
        if [[ -n "${INPUTS_BUILD_WORKFLOW_NAME}" ]]; then
          printf 'RAPIDS_BUILD_WORKFLOW_NAME=%s\n' "$(printf '%s' "${INPUTS_BUILD_WORKFLOW_NAME}" | tr -d '\n')" | tee --append "${GITHUB_ENV}" "${GITHUB_OUTPUT}"
        fi
      env:
        INPUTS_REPO: ${{ inputs.repo || github.repository }}
        INPUTS_BRANCH: ${{ inputs.branch || github.ref_name }}
        INPUTS_SHA: ${{ inputs.sha }}
        INPUTS_DATE: ${{ inputs.date }}
        INPUTS_BUILD_WORKFLOW_NAME: ${{ inputs.build_workflow_name }}
