name: Dispatch to summarize
description: |
  The purpose of this wrapper is to keep it easy for external consumers to switch branches of
  the shared-actions repo when they are changing something about shared-actions and need to test it
  in their pipelines.

  This script is meant to be standalone in that it should not require external inputs from
  consumers. Consumers may set SHARED_ACTIONS_REPO and SHARED_ACTIONS_REF to test changes
  in their customized shared-actions repo, but they should not add inputs to those scripts.
  Instead, they should add those inputs to the variables that get stashed in
  telemetry-impls/stash-base-env-vars.
inputs:
  cert_concat:
    description: Concatenation of certs (CA;Client;ClientKey)
  extra_attributes:
    description:
      Additional attributes to add to OTEL_RESOURCE_ATTRIBUTES.
      See https://opentelemetry.io/docs/languages/sdk-configuration/general/#otel_resource_attributes

runs:
  using: 'composite'
  steps:
    - name: Clone shared-actions repo
      uses: actions/checkout@v4
      with:
        repository: ${{ env.SHARED_ACTIONS_REPO || 'rapidsai/shared-actions' }}
        ref: ${{ env.SHARED_ACTIONS_REF || 'telemetry-dispatch-actions' }}
        path: ./shared-actions
    # This is necessary because this action will generally be run in a job separately from
    # where the env vars are set
    - name: Load base environment variables
      uses: ./shared-actions/telemetry-impls/load-base-env-vars
    - name: Run summarize action
      uses: ./shared-actions/telemetry-impls/summarize
      with:
        cert_concat: ${{ inputs.cert_concat }}
        extra_attributes: ${{ inputs.extra_attributes }}
