name: telemetry-dispatch-stash-base-env-vars
description: |
  Stores base environment variables in a file and uploads that file
  as an artifact.

  This action should only be called once in a build,
  at the start of the top-level workflow. All other jobs in the top
  level workflow should come after this job. It is generally enough
  to have only the checks and devcontainers jobs explicitly depend on
  it and have everything else be downstream of them.

inputs:
  shared_actions_repo:
    default: rapidsai/shared-actions
    description: "repository to clone for shared actions"
  shared_actions_ref:
    default: main
    description: "branch to clone for shared actions"

runs:
  using: 'composite'
  steps:
    - name: Clone shared-actions repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.shared_actions_repo }}
        ref: ${{ inputs.shared_actions_ref }}
        path: ./shared-actions
    - name: Stash base env vars
      uses: ./shared-actions/telemetry-impls/stash-base-env-vars
