name: Load environment variables from a file and set them in the current env
description: |
  This script is the counterpart to _stash-base-env-vars. It is called by child shared-workflows
  to load variables that are set by the top-level workflow.

  This script will be called only by the child workflows. The parent workflow should not need
  to reload the values here, and it also should not need access to child workflow variables.

runs:
  using: 'composite'
  steps:
    - name: Download base environment variables file
      uses: actions/download-artifact@v4
      with:
        name: telemetry-env-vars
    - name: Set environment variables from file into GITHUB_ENV
      shell: bash
      # Only set the env var if it is not already set
      # the ${!VARIABLE} syntax is called "indirect expansion" and it is kind of equivalent to ${${env_var_name}}
      #      in other words, expand to find the variable name, then dereference that variable name
      # The goofy env_var_value filtering through tr is to ensure that the strings don't include quotes.
      run: |
        while read LINE; do
          env_var_name="$( cut -d '=' -f 1 <<< "$LINE" )";
          if [ "${!env_var_name}" = "" ]; then
            env_var_value="$(echo ${LINE#*=} | tr -d '"')"
            echo "${env_var_name}=$(echo "${env_var_value}" | sed 's/^,//')" >> ${GITHUB_ENV};
          else
            echo "Load base env info: ignoring new value for "${env_var_name}" in loading base env vars. It is already set to "${!env_var_name}"." >&2;
          fi
        done <telemetry-env-vars
