name: 'Clone/checkout specific fork/ref of shared-actions repo and call its load-base-env-vars script'
description: |
  The purpose of this wrapper is to keep it easy for external consumers to switch branches of
  the shared-actions repo when they are changing something about shared-actions and need to test it
  in their pipelines.

  Outputs here are all assumed to be env vars set in the calling environment
inputs:
  load_service_name:
    description: |
      If true, loads OTEL_SERVICE_NAME from the stashed env vars. This is used for top-level workflows.
      Otherwise the telemetry service name is obtained from Github job metadata. This is for child workflows.
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Clone shared-actions repo
      uses: actions/checkout@v4
      with:
        repository: ${{ env.SHARED_ACTIONS_REPO}}
        ref: ${{ env.SHARED_ACTIONS_REF}}
        path: ./shared-actions
    - name: Set OTEL_SERVICE_NAME from job if not loading from stash
      if: ${{ inputs.load_service_name != 'true' }}
      uses: ./shared-actions/telemetry-impls/set-otel-service-name
    - name: Load base env vars
      uses: ./shared-actions/telemetry-impls/load-base-env-vars
