name: load-then-clone
description: |
  This is a kind of bootstrapping action. Environment variables do not
  transfer between top-level workflows and child workflows. We have to
  pass them another way. We could use inputs and outputs, but that would
  proliferate lots of boilerplate.

  We use a scheme where the top-level workflows store environment variables
  in files, and child workflows download those files and re-hydrate the
  environment in their context. There are two variables that are especially
  tricky, though. We allow users to specify their own repo and ref for where
  to get the `shared-actions` repo. That info is in the shared file, but we
  have to clone a `shared-actions` repo to use its script to load the variables.
  As a result, we clone the code twice: first to learn how to load the variables,
  then another time when the variables are actually set.

inputs:
  GH_TOKEN:
    required: true
    description: |
      The GitHub token to use to download the base environment variables file.

runs:
  using: 'composite'
  steps:
    # Installing the download-artifact action with pnpm is definitely a hack.
    # The download-artifact action ALWAYS shows an error when a file is not found.
    # There is no way to fail silently. Re-runs won't run the initial telemetry-setup,
    # so the env vars file will be missing, and these downloads would fail. This
    # was noisy and confusing to developers. This hack gives us better error handling.
    - name: Set up node to run download script
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    - name: Install dependencies
      shell: bash
      run: npm install actions/download-artifact@v4 actions/github-script@v7
    - name: Download base environment variables file
      shell: node
      run: |
        const { downloadArtifact } = require('actions/download-artifact');
        const { exportVariable } = require('actions/github-script');
        try {
          downloadArtifact({
            repo: '${{ github.repository }}',
            ref: '${{ github.ref }}',
            workflow: 'telemetry-dispatch-setup',
            artifact: 'telemetry-tools-env-vars',
            token: '${{ inputs.GH_TOKEN }}'
          });
          exportVariable('TELEMETRY_ENABLED', 'true');
        } catch (error) {
          console.log('Download of base env vars file failed. Telemetry is disabled.');
          exportVariable('TELEMETRY_ENABLED', 'false');
        }
    - name: Download base environment variables file
      if: ${{ env.TELEMETRY_ENABLED == 'true' }}
      shell: bash
      run: unzip telemetry-tools-env-vars.zip
    # We can't use ./telemetry-implementation/load-base-env-vars here
    # because at this point we have not cloned the repo.
    - name: Set environment variables from file into GITHUB_ENV
      if: ${{ env.TELEMETRY_ENABLED == 'true' }}
      shell: bash
      # Only set the env var if it is not already set
      # the ${!VARIABLE} syntax is called "indirect expansion" and it is kind of equivalent to ${${env_var_name}}
      #      in other words, expand to find the variable name, then dereference that variable name
      # The goofy env_var_value filtering through tr is to ensure that the strings don't include quotes.
      run: |
        while read LINE; do
          env_var_name="$( cut -d '=' -f 1 <<< "$LINE" )";
          if [ "${!env_var_name}" = "" ]; then
            env_var_value="$(echo ${LINE#*=} | tr -d '"')"
            echo "${env_var_name}=$(echo "${env_var_value}" | sed 's/^,//')" >> ${GITHUB_ENV};
          else
            echo "Load base env info: ignoring new value for "${env_var_name}" in loading base env vars. It is already set to "${!env_var_name}"." >&2;
          fi
        done <telemetry-env-vars
    - name: Clone shared-actions repo with loaded env vars
      uses: actions/checkout@v4
      with:
        repository: ${{ env.SHARED_ACTIONS_REPO }}
        ref: ${{ env.SHARED_ACTIONS_REF }}
        path: ./shared-actions
