name: telemetry-dispatch-setup
description: |
  This script sets important environment variables that may be used by tools that
  implement OpenTelemetry. This script also stores attributes (metadata) for the
  current job, so that this metadata can be associated with spans during the final
  parsing of job metadata.

  Obtains GitHub Actions job list and matches current job using runner name and attempt number.

  This action should be called at the beginning of child workflows, generally as the first
  step in any job other than computing the matrix.

inputs:
  extra_attributes:
    description: "comma-separated key=value attributes to associate with the current job"

runs:
  using: 'composite'
  steps:
    - uses: rapidsai/shared-actions/telemetry-impls/load-then-clone@main
      id: has_base_env_var_artifact
    - name: Output that setup was skipped if the base env var artifact was not found
      if: steps.has_base_env_var_artifact.outputs.artifact_found == 'false'
      shell: bash
      run: echo "Skipping telemetry-setup because base env var artifact was not found"
    - name: Creating folder for job-created telemetry artifacts
      shell: bash
      run: mkdir -p telemetry-artifacts
    - uses: ./shared-actions/telemetry-impls/github-actions-job-info
      if: steps.has_base_env_var_artifact.outputs.artifact_found == 'true'
    - shell: bash
      if: steps.has_base_env_var_artifact.outputs.artifact_found == 'true'
      run:
        echo JOB_ID="$(cat job_info.json | jq -r '.id')" >> ${GITHUB_ENV};
    # overrides loaded value.
    - name: Set OTEL_SERVICE_NAME from job
      if: steps.has_base_env_var_artifact.outputs.artifact_found == 'true'
      uses: ./shared-actions/telemetry-impls/set-otel-service-name
    - name: Add attribute metadata beyond the stashed basic stuff
      if: steps.has_base_env_var_artifact.outputs.artifact_found == 'true'
      shell: bash
      run:
        attributes="${OTEL_RESOURCE_ATTRIBUTES}";
        labels="$(jq -r '.labels | join(" ")' job_info.json)";
        if [ "${labels}" != "" ]; then
          attributes="${attributes},rapids.labels=${labels}";
        fi;
        if [ "${{ inputs.extra_attributes }}" != "" ]; then
          attributes="${attributes},${{ inputs.extra_attributes }}";
        fi;
        attributes=$(echo "${attributes}" | sed 's/^,//');
        attributes=$(echo "${attributes}" | sed 's/,$//');
        attributes=$(echo "${attributes}" | sed -r "s/(git.job_url=[^,]+)/\1\/job\/${JOB_ID}/");
        echo OTEL_RESOURCE_ATTRIBUTES="${attributes}" >> ${GITHUB_ENV};
