name: check-nightly-success
description: Check if the nightlies have succeeded recently.

# these inputs should all be 'required: true' without defaults... this action should only
# ever be invoked by check_nightly_success/dispatch
inputs:
  repo:
    description: "Repository name with owner (e.g. 'rapidsai/cudf' not 'cudf')"
    required: true
    type: string
  target_branch:
    description: |
      Branch the pull request this is running on targets.
      Only statuses of nightly runs on that branch will be considered.
    required: true
    type: string
  workflow_id:
    description: "The workflow whose runs to check"
    required: true
    type: string
  max_days_without_success:
    description: "The number of consecutive days that may go by without a successful CI run"
    required: true
    type: integer

runs:
  using: composite
  steps:
    - name: Run the Python script
      shell: bash
      env:
        REPO: ${{ inputs.repo }}
        TARGET_BRANCH: ${{ inputs.target_branch }}
        WORKFLOW_ID: ${{ inputs.workflow_id }}
        MAX_DAYS_WITHOUT_SUCCESS: ${{ inputs.max_days_without_success }}
      run: |
          python -m pip install \
            --prefer-binary \
            'requests>=2.32.4'
          python shared-actions/check_nightly_success/check-nightly-success/check.py \
            --repo ${REPO} \
            --branch ${TARGET_BRANCH} \
            --workflow-id ${WORKFLOW_ID} \
            --max-days-without-success ${MAX_DAYS_WITHOUT_SUCCESS}
