name: telemetry-dispatch-summarize
description: |
  This action is run in a final job on the top-level workflow, after all other
  jobs are completed. This action downloads the JSON records of all jobs from
  the current run. It then associates metadata records that were uploaded with
  the telemetry-dispatch-stash-job-artifacts action with jobs. This is
  effectively label metadata. Finally, this action creates OpenTelemetry spans
  with the timing and label metadata, and sends it to the configured Tempo
  endpoint (or forwarder).
inputs:
  OTEL_SERVICE_NAME:
    description: "Name of the top-level workflow"
  shared_actions_repo:
    description: "Repository to download the telemetry-impls from"
    default: "rapidsai/shared-actions"
  shared_actions_ref:
    description: "Reference to download the telemetry-impls from"
    default: "main"
  OTEL_EXPORTER_OTLP_ENDPOINT:
    description: "OTLP endpoint to send traces to"
    default: "https://alloy.local.gha-runners.nvidia.com:4317"
  OTEL_TRACES_EXPORTER:
    description: "OTLP exporter to use"
    default: "otlp"
  OTEL_EXPORTER_OTLP_PROTOCOL:
    description: "OTLP protocol to use"
    default: "grpc"
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ inputs.shared_actions_repo }}
        ref: ${{ inputs.shared_actions_ref }}
        path: shared-actions
    - uses: ./shared-actions/telemetry-impls/summarize
      with:
        OTEL_SERVICE_NAME: ${{ inputs.OTEL_SERVICE_NAME }}
        OTEL_EXPORTER_OTLP_ENDPOINT: ${{ inputs.OTEL_EXPORTER_OTLP_ENDPOINT }}
        OTEL_TRACES_EXPORTER: ${{ inputs.OTEL_TRACES_EXPORTER }}
        OTEL_EXPORTER_OTLP_PROTOCOL: ${{ inputs.OTEL_EXPORTER_OTLP_PROTOCOL }}
