name: telemetry-dispatch-summarize
description: |
  This action is run in a final job on the top-level workflow, after all other
  jobs are completed. This action downloads the JSON records of all jobs from
  the current run. It then associates metadata records that were uploaded with
  the telemetry-dispatch-stash-job-artifacts action with jobs. This is
  effectively label metadata. Finally, this action creates OpenTelemetry spans
  with the timing and label metadata, and sends it to the configured Tempo
  endpoint (or forwarder).

inputs:
  GH_TOKEN:
    required: true
    description: "GitHub token to use to check for artifact"

runs:
  using: 'composite'
  steps:
    - uses: rapidsai/shared-actions/telemetry-impls/load-then-clone@check-base-env-var-artifact
      if: ${{ github.run_attempt == '1' }}
      with:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
    - uses: ./shared-actions/telemetry-impls/summarize
      if: ${{ github.run_attempt == '1' }}
    - if: ${{ github.run_attempt != '1' }}
      shell: bash
      run: echo "Skipping telemetry-summarize for run attempt > 1"
