name: 'Telemetry summarize'
description: |
  Consumes job info, parses into spans, and pushes spans.

runs:
  using: 'composite'
  steps:
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: 'pip'
        cache-dependency-path: './shared-actions/telemetry-impls/summarize/requirements.txt'
    - name: Install dependencies
      run: pip install -r './shared-actions/telemetry-impls/summarize/requirements.txt'
      shell: bash
    # Writes JSON file that jobs below consume
    - uses: ./shared-actions/telemetry-impls/github-actions-job-info
      id: github-job-info
      with:
        all_jobs: true
    - name: Upload job JSON file if debugging
      uses: actions/upload-artifact@v4
      if: runner.debug == '1'
      with:
        name: telemetry-tools-all_jobs.json
        path: all_jobs.json
    # This downloads ALL of the files that we have collected from each job.
    - uses: actions/download-artifact@v4
      with:
        path: telemetry-artifacts
        pattern: telemetry-tools-*
        merge-multiple: true

    - name: Run parse and send trace/spans to endpoint
      shell: bash
      run: |
        timeout 5m python3 ./shared-actions/telemetry-impls/summarize/send_trace.py
    - name: Clean up attributes artifacts from all jobs
      uses: ./shared-actions/telemetry-impls/clean-up-artifacts
    # Telemetry jobs should never affect the pass/fail status of the overall CI
    - name: Exit success
      if: always()
      continue-on-error: true
      shell: bash
      run: |
        exit 0
