name: check-version-against-tag
description: Check if the `VERSION` file matches the git tag.

runs:
  using: composite
  steps:
    - name: Run the Python script
      shell: bash
      run: |
        python -m pip install dunamai
        expected_version="$(python -m dunamai from git --format '{base}')"
        if [ "$expected_version" != "$(cat VERSION)" ]; then
          echo "Expected VERSION file to be \"$expected_version\", got:"
          cat VERSION
          exit 1
        fi
