name: dispatch-stash-job-artifacts
description: |
  Clones a particular branch/ref of a shared-actions repo, then
  call the stash-artifacts implementation script, which writes
  some environment variables so that downstream jobs can refer to them.

inputs:
  json_params:
    type: string
    default: "{}"
    description: "JSON string of parameters. Used to avoid 10-param limit on workflow inputs."

runs:
  using: 'composite'
  steps:
    - name: Handle empty inputs
      id: handle-empty-inputs
      shell: bash
      run: |
        echo "shared_actions_repo=${{ fromJson(inputs.json_params).shared_actions_repo || 'rapidsai/shared-actions' }}" >> $GITHUB_OUTPUT
        echo "shared_actions_ref=${{ fromJson(inputs.json_params).shared_actions_ref || 'main' }}" >> $GITHUB_OUTPUT
    - uses: actions/checkout@v4
      with:
        repository: ${{ steps.handle-empty-inputs.outputs.shared_actions_repo }}
        ref: ${{ steps.handle-empty-inputs.outputs.shared_actions_ref }}
        path: ./shared-actions
    # Stash current job's OTEL_RESOURCE_ATTRIBUTES and any files in the telemetry-artifacts directory
    - name: Stash job artifacts
      uses: ./shared-actions/telemetry-impls/stash-job-artifacts
